theme: jekyll-theme-architect

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-112127128-2

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

  
 